-- Migration: Go-managed authentication
-- Supabase is used only as PostgreSQL. Authentication data and sessions
-- are owned by the Go API.

-- The foundation migration intentionally kept employee authentication
-- provider-agnostic. These columns make the existing employee records
-- compatible with the Go authentication service.
ALTER TABLE employees
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255),
    ADD COLUMN IF NOT EXISTS display_name VARCHAR(200),
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS permission_version INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS login_attempts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_employees_email_lower
    ON employees (LOWER(email));

CREATE INDEX IF NOT EXISTS idx_company_users_email_lower
    ON company_users (LOWER(email))
    WHERE deleted_at IS NULL;

-- Opaque tokens are generated by Go and only their SHA-256 digests are
-- persisted. This makes a database leak insufficient to authenticate.
CREATE TABLE IF NOT EXISTS auth_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    family_id UUID NOT NULL DEFAULT uuid_generate_v4(),
    principal_type VARCHAR(32) NOT NULL
        CHECK (principal_type IN ('company_user', 'employee')),
    principal_id UUID NOT NULL,
    access_token_hash BYTEA NOT NULL UNIQUE,
    refresh_token_hash BYTEA NOT NULL UNIQUE,
    access_expires_at TIMESTAMPTZ NOT NULL,
    refresh_expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_agent TEXT,
    ip_address INET,
    replaced_by_session_id UUID REFERENCES auth_sessions(id),
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_principal
    ON auth_sessions (principal_type, principal_id)
    WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_auth_sessions_family
    ON auth_sessions (family_id)
    WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS auth_email_tokens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    principal_type VARCHAR(32) NOT NULL
        CHECK (principal_type IN ('company_user', 'employee')),
    principal_id UUID NOT NULL,
    purpose VARCHAR(32) NOT NULL
        CHECK (purpose IN ('verify_email', 'reset_password')),
    token_hash BYTEA NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auth_email_tokens_lookup
    ON auth_email_tokens (token_hash, purpose)
    WHERE used_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_auth_email_tokens_principal
    ON auth_email_tokens (principal_type, principal_id, purpose)
    WHERE used_at IS NULL;