// Task 59 — i18n مصغّر بدون كود توليد: خريطتان ثابتتان (ar/en) مطابقتان
// لروح مفاتيح تطبيق الويب (auth.json) مع مفاتيح الشاشات الجديدة.
// الترجمة تُختار من LocaleProvider وتمرر عبر context.tr('key').

const Map<String, String> _ar = <String, String>{
  // عام
  'ok': 'حسناً',
  'save': 'حفظ',
  'skip': 'تخطي',
  'next': 'متابعة',
  'back': 'رجوع',
  'loading': 'جارٍ التحميل...',
  'retry': 'إعادة المحاولة',
  'error_generic': 'حدث خطأ غير متوقع، حاول مرة أخرى',
  'network_error': 'تعذر الوصول إلى الخادم — تحقق من اتصالك وعنوان الخادم',
  // دخول
  'login_title': 'تسجيل الدخول',
  'login_subtext': 'أدخل بيانات حساب صيدليتك للمتابعة',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'login_btn': 'دخول',
  'logging_in': 'جارٍ الدخول...',
  'no_account': 'ليس لديك حساب؟',
  'create_account': 'أنشئ حساب صيدلية جديدة',
  'advanced_server': 'عنوان الخادم (متقدم)',
  'server_url': 'عنوان الـ API',
  'server_invalid': 'العنوان يجب أن يبدأ بـ http:// أو https://',
  // تسجيل حساب جديد
  'reg_title': 'حساب صيدلية جديد',
  'reg_subtext': 'دقيقة واحدة وتصبح جاهزاً — نبدأ بالتحقق من بريدك',
  'reg_company_name': 'اسم الصيدلية',
  'reg_company_email': 'بريد الصيدلية الرسمي',
  'reg_first_name': 'الاسم الأول',
  'reg_last_name': 'الاسم الأخير',
  'reg_email': 'بريدك الشخصي (اسم المستخدم)',
  'reg_password': 'كلمة المرور',
  'reg_submit': 'إنشاء الحساب وإرسال الرمز',
  'reg_success_verify': 'أرسلنا رمز التحقق إلى بريدك — أدخله في الشاشة التالية',
  // تحقق البريد
  'verify_title': 'تأكيد البريد الإلكتروني',
  'verify_subtext': 'أدخل الرمز المكوَّن من 6 أرقام المُرسَل إلى {email}',
  'verify_code': 'رمز التحقق',
  'verify_btn': 'تأكيد وفتح الجلسة',
  'verifying': 'جارٍ التحقق...',
  'resend': 'إعادة إرسال الرمز',
  'resend_in': 'يمكنك طلب رمز جديد بعد {n} ثانية',
  'verify_success_onboarding': 'تم التأكيد! جارٍ فتح معالج إعداد صيدليتك...',
  'verify_success_home': 'تم التأكيد! جارٍ فتح لوحتك...',
  'verify_fallback_login': 'تم تأكيد بريدك لكن جلسة الدخول لم تفتح — سجّل دخولك الآن',
  // معالج الإعداد
  'ob_title': 'إعداد صيدليتك',
  'ob_step': 'الخطوة {n} من 4',
  'ob_welcome_title': 'أهلاً بك! ما اسم صيدليتك؟',
  'ob_welcome_hint': 'هذا الاسم سيظهر في الفواتير والتقارير — يمكنك تعديله لاحقاً',
  'ob_contact_title': 'كيف يتواصل معك العملاء؟',
  'ob_contact_hint': 'اختياري — يمكنك تخطيه الآن وإكماله لاحقاً',
  'ob_location_title': 'أين تقع صيدليتك؟',
  'ob_location_hint': 'اختياري — يساعد في التقارير والتوصيل',
  'ob_review_title': 'راجع معلومات صيدليتك',
  'ob_review_edit': 'تعديل',
  'ob_name': 'اسم الصيدلية',
  'ob_phone': 'رقم الهاتف',
  'ob_website': 'الموقع الإلكتروني',
  'ob_address1': 'العنوان (سطر 1)',
  'ob_address2': 'العنوان (سطر 2)',
  'ob_city': 'المدينة',
  'ob_state': 'المحافظة/الولاية',
  'ob_postal': 'الرمز البريدي',
  'ob_name_required': 'اسم الصيدلية مطلوب (حرفان على الأقل)',
  'ob_saving': 'جارٍ الحفظ...',
  'ob_complete_title': 'كل شيء جاهز!',
  'ob_complete_sub': 'تم إعداد صيدليتك بنجاح — افتتح اللوحة الآن',
  'ob_enter': 'الدخول إلى اللوحة',
  // اللوحة
  'tab_dashboard': 'الرئيسية',
  'tab_products': 'الأدوية',
  'tab_settings': 'الإعدادات',
  'hello_user': 'مرحباً {name}',
  'stat_products': 'إجمالي الأصناف',
  'stat_low_stock': 'أصناف شبه نافدة',
  'stat_active_employees': 'الموظفون النشطون',
  'stat_active_today': 'حاضرون اليوم',
  'stat_sales_today': 'وحدات مباعة اليوم',
  'low_stock_title': 'أصناف تحتاج إعادة تعبئة',
  'low_stock_empty': 'لا أصناف تحت الحد الأدنى — مخزونك سليم',
  'units': 'وحدة',
  // الأدوية
  'products_search_hint': 'ابحث بالاسم أو الباركود...',
  'products_empty': 'لا نتائج — جرّب كلمة أخرى',
  'products_count': '{n} صنف',
  'per_box': 'العلبة',
  'strip': 'الشريط',
  // الإعدادات
  'settings_language': 'لغة الواجهة',
  'settings_lang_ar': 'العربية',
  'settings_lang_en': 'English',
  'settings_server': 'عنوان الخادم',
  'settings_server_saved': 'تم الحفظ — سيتم إعادة تسجيل الدخول من الخادم الجديد',
  'settings_logout': 'تسجيل الخروج',
  'settings_version': 'الإصدار',
  'logout_failed': 'تعذر تسجيل الخروج من الخادم — تم مسح الجلسة محلياً',
};

const Map<String, String> _en = <String, String>{
  'ok': 'OK',
  'save': 'Save',
  'skip': 'Skip',
  'next': 'Continue',
  'back': 'Back',
  'loading': 'Loading...',
  'retry': 'Retry',
  'error_generic': 'Unexpected error, please try again',
  'network_error': 'Cannot reach the server — check your connection and server URL',
  'login_title': 'Sign in',
  'login_subtext': 'Enter your pharmacy account credentials to continue',
  'email': 'Email',
  'password': 'Password',
  'login_btn': 'Sign in',
  'logging_in': 'Signing in...',
  'no_account': "Don't have an account?",
  'create_account': 'Create a new pharmacy account',
  'advanced_server': 'Server URL (advanced)',
  'server_url': 'API base URL',
  'server_invalid': 'URL must start with http:// or https://',
  'reg_title': 'New pharmacy account',
  'reg_subtext': 'One minute and you are ready — we start with email verification',
  'reg_company_name': 'Pharmacy name',
  'reg_company_email': 'Official pharmacy email',
  'reg_first_name': 'First name',
  'reg_last_name': 'Last name',
  'reg_email': 'Your personal email (username)',
  'reg_password': 'Password',
  'reg_submit': 'Create account & send code',
  'reg_success_verify': 'We sent a verification code — enter it on the next screen',
  'verify_title': 'Confirm your email',
  'verify_subtext': 'Enter the 6-digit code sent to {email}',
  'verify_code': 'Verification code',
  'verify_btn': 'Confirm & open session',
  'verifying': 'Verifying...',
  'resend': 'Resend code',
  'resend_in': 'You can request a new code in {n}s',
  'verify_success_onboarding': 'Confirmed! Opening your pharmacy setup wizard...',
  'verify_success_home': 'Confirmed! Opening your dashboard...',
  'verify_fallback_login': 'Email confirmed but the session was not opened — please sign in',
  'ob_title': 'Set up your pharmacy',
  'ob_step': 'Step {n} of 4',
  'ob_welcome_title': 'Welcome! What is your pharmacy called?',
  'ob_welcome_hint': 'This name appears on invoices and reports — editable later',
  'ob_contact_title': 'How should customers reach you?',
  'ob_contact_hint': 'Optional — skip now and complete later',
  'ob_location_title': 'Where is your pharmacy located?',
  'ob_location_hint': 'Optional — helps with reports and delivery',
  'ob_review_title': 'Review your pharmacy information',
  'ob_review_edit': 'Edit',
  'ob_name': 'Pharmacy name',
  'ob_phone': 'Phone number',
  'ob_website': 'Website',
  'ob_address1': 'Address (line 1)',
  'ob_address2': 'Address (line 2)',
  'ob_city': 'City',
  'ob_state': 'State / Province',
  'ob_postal': 'Postal code',
  'ob_name_required': 'Pharmacy name is required (2+ letters)',
  'ob_saving': 'Saving...',
  'ob_complete_title': 'Everything is ready!',
  'ob_complete_sub': 'Your pharmacy is set up — open the dashboard now',
  'ob_enter': 'Open dashboard',
  'tab_dashboard': 'Home',
  'tab_products': 'Medicines',
  'tab_settings': 'Settings',
  'hello_user': 'Hello {name}',
  'stat_products': 'Total products',
  'stat_low_stock': 'Low stock items',
  'stat_active_employees': 'Active employees',
  'stat_active_today': 'Present today',
  'stat_sales_today': 'Units sold today',
  'low_stock_title': 'Items needing restock',
  'low_stock_empty': 'No items below minimum — stock is healthy',
  'units': 'units',
  'products_search_hint': 'Search by name or barcode...',
  'products_empty': 'No results — try another keyword',
  'products_count': '{n} products',
  'per_box': 'Box',
  'strip': 'Strip',
  'settings_language': 'Interface language',
  'settings_lang_ar': 'العربية',
  'settings_lang_en': 'English',
  'settings_server': 'Server URL',
  'settings_server_saved': 'Saved — you will sign in against the new server',
  'settings_logout': 'Sign out',
  'settings_version': 'Version',
  'logout_failed': 'Server logout failed — session cleared locally',
};

String trFor(String locale, String key) {
  final map = locale == 'en' ? _en : _ar;
  return map[key] ?? _ar[key] ?? key;
}

/// تعويض المتغيرات البسيطة: {email} {n} {name}
String trFmt(String locale, String key, Map<String, String> vars) {
  var s = trFor(locale, key);
  vars.forEach((k, v) {
    s = s.replaceAll('{$k}', v);
  });
  return s;
}
